### ISSUE TITLE
Getting error on downwards OpenBSD

### ISSUE THREAD

**Issue by ghost** [noqqe/downwards#2]
<pre>
Traceback (most recent call last):
  File "/usr/sbin/downwards", line 33, in <module>
    sys.exit(load_entry_point('downwards==1.3.0', 'console_scripts', 'downwards')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/downwards/__init__.py", line 206, in main
    rendered = render_article(article=result, language=language, template=mandoc, date=str(datetime.date.today()))
  File "/usr/lib/python3.8/site-packages/downwards/__init__.py", line 158, in render_article
    content = flatten_content_hierarchy(article=article, language=language)
  File "/usr/lib/python3.8/site-packages/downwards/__init__.py", line 138, in flatten_content_hierarchy
    flt = flt + ".Sh " + section.title + n
TypeError: can only concatenate str (not "NoneType") to str
</pre>

**Comment by noqqe** [comment]
Thanks for reporting this! I fixed it :)
